config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers, controllers: {
    sessions: 'teachers/sessions',
    registrations: 'teachers/registrations',
    passwords: 'teachers/passwords'
  }

  root "students#index"

  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :teacher

  validates :name, :subject_name, :marks, presence: true
  validates :marks, numericality: { greater_than_or_equal_to: 0 }
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :students, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit update destroy]
  before_action :authenticate_teacher!

  def index
    @students = current_teacher.students.all.order(updated_at: :desc)
  end

  def show
  end

  def new
    @student = Student.new
	end
  
  def create
	  # Find existing student by name and subject_name
	  @existing_student = Student.find_by(name: student_params[:name], subject_name: student_params[:subject_name])

	  if @existing_student
	    # If found, update the marks with new marks to the existing ones
	    @existing_student.marks = student_params[:marks].to_i
	    if @existing_student.save
	      flash[:notice] = 'Marks were successfully updated for the existing student.'
	      respond_to do |format|
	        format.turbo_stream
	        format.html { redirect_to students_path }
	      end
	    else
	      flash[:alert] = 'Failed to update marks for the existing student.'
	      render :new, status: :unprocessable_entity
	    end
	  else
	    # If not found, create a new student
	    @student = Student.new(student_params)
	    if @student.save
	      flash[:notice] = 'Student was successfully created.'
	      respond_to do |format|
	        format.turbo_stream
	        format.html { redirect_to students_path }
	      end
	    else
	      render :new, status: :unprocessable_entity
	    end
	  end
	end


  def edit
    respond_to do |format|
      format.turbo_stream
      format.html { render :edit }
    end
  end

  def update
	  if @student.update(student_params)
	  	flash[:notice] = 'Student was successfully updated.'
	    respond_to do |format|
	      format.json { head :no_content }
	      format.turbo_stream 
	    end
	  else
	    render json: { error: "Update failed" }, status: :unprocessable_entity
	  end
	end


  def destroy
    @student.destroy
    redirect_to root_path, notice: "Student was successfully deleted."
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :subject_name, :marks, :teacher_id)
  end
end

app/controllers/teachers/confirmations_controller.rb
# frozen_string_literal: true

class Teachers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/teachers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Teachers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/teachers/passwords_controller.rb
# frozen_string_literal: true

class Teachers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/teachers/registrations_controller.rb
# frozen_string_literal: true

class Teachers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/teachers/sessions_controller.rb
# frozen_string_literal: true

class Teachers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/teachers/unlocks_controller.rb
# frozen_string_literal: true

class Teachers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
		case level
		when :notice then 'alert alert-success'
		when :alert then 'alert alert-danger'
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeacherPor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%# Google Fonts %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Poppins&display=swap" rel="stylesheet">

    <%# Font Awesome CDN %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <%= render 'shared/header' %>
    <div id="flash-messages">
      <%= render 'shared/flash' %>
    </div>
    <%= yield %>
    <%= turbo_frame_tag 'remote_modal' %>
  </body>
</html>

app/views/shared/_flash.html.erb
<div id="flash">
	<% flash.each do |key, value| %>
		<div class="<%= flash_class(key.to_sym) %> alert-dismissible fade show" role="alert">
			<% unless value == true %>
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				<%= value %>
			<% end %>
		</div>
	<% end %>
</div>

app/views/shared/_header.html.erb
<% if teacher_signed_in? %>
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Teacher Portal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <% if teacher_signed_in? %>
            <%= link_to 'Sign Out', destroy_teacher_session_path, class: 'nav-link active' %>
          <% else %>
            <%= link_to 'Sign In', new_teacher_session_path, class: 'nav-link active' %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<% end %>

app/views/shared/_turbo_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" id="bsTurboModal" tabindex="-1" aria-labelledby="bsTurboModalLabel" aria-hidden="true" data-controller="bs-modal">
    <div class="modal-dialog">
      <div class="modal-content rounded-0">
        <div class="modal-header">
          <h5 class="modal-title" id="bsTurboModalLabel"><%= modal_title %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= render form_partial %>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<div class="container p-4">
	<%= form_with(model: @student) do |form| %>
	  <div class="modal-body">

	  	<% if @student.errors.any? %>
        <div class="alert alert-danger rounded-0">
          <h4><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h4>
          <ul>
            <% @student.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

		  <%= form.hidden_field :teacher_id, value: current_teacher.id %>
		  <div class="form-group">
			  <%= form.label :name %>
			  <div class="input-group mt-2 mb-2">
			    <span class="input-group-text rounded-0" id="basic-addon1"><i class="fa-solid fa-user"></i></span>
			    <%= form.text_field :name, class: 'form-control rounded-0', 'aria-describedby': 'basic-addon1' %>
			  </div>
			</div>

			<div class="form-group">
			  <%= form.label :subject_name, 'Subject'%>
			  <div class="input-group mt-2 mb-2">
			    <span class="input-group-text rounded-0" id="basic-addon1"><i class="fa-solid fa-book"></i></span>
			    <%= form.text_field :subject_name, class: 'form-control rounded-0', 'aria-describedby': 'basic-addon1' %>
			  </div>
			</div>

			<div class="form-group">
			  <%= form.label :marks, 'Mark'%>
			  <div class="input-group mt-2 mb-2">
			    <span class="input-group-text rounded-0" id="basic-addon1"><i class="fa-solid fa-bookmark"></i></span>
			    <%= form.text_field :marks, class: 'form-control rounded-0', 'aria-describedby': 'basic-addon1' %>
			  </div>
			</div>

		  <div class="text-center">
		    <%= form.submit class: 'btn btn-primary w-50 btn-dark rounded-0 py-2 mt-2', data: { action: 'click->bs-modal#submitEnd' } %>
		  </div>
	  </div>
	<% end %>
</div>

app/views/students/_student.html.erb
<tr id="<%= dom_id(student) %>">
  <td>
    <span class="avatar"><%= student.name[0].upcase %></span>
  </td>
  <td data-controller="editable" data-editable-field="name" data-editable-url="<%= student_path(student) %>" contenteditable="true">
    <%= student.name %>
    </td>
  <td data-controller="editable" data-editable-field="subject_name" data-editable-url="<%= student_path(student) %>" contenteditable="true"><%= student.subject_name %></td>
  <td data-controller="editable" data-editable-field="marks" data-editable-url="<%= student_path(student) %>" contenteditable="true"><%= student.marks %></td>
  <td>
    <div class="dropdown">
      <button class="btn btn-dark dropdown-toggle btn-sm" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      </button>
      <ul class="dropdown-menu rounded-0">
        <%= link_to 'Edit', edit_student_path(student), class: "dropdown-item", data: { controller: "bs-modal-form" } %>
        <%= link_to 'Delete', student_path(student), class: "dropdown-item",  data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
      </ul>
    </div>
  </td>
</tr>

app/views/students/create.turbo_stream.erb
<%= turbo_stream.replace "flash-messages", partial: "shared/flash" %>
<% if @existing_student.present? %>
  <%= turbo_stream.replace "student_#{@existing_student.id}", partial: "students/student", locals: { student: @existing_student } %>
<% else %>
  <%= turbo_stream.append "student-list", partial: "students/student", locals: { student: @student } %>
<% end %>

app/views/students/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'shared/turbo_modal', modal_title: 'Edit Student', form_partial: 'students/form' %>
<% end %>

app/views/students/index.html.erb
<div class="container mt-5">
	<h3>Students List</h3>
	<div class="table-responsive table-sm">
	 <table class="table">
	 	<thead>
	 		<tr>
	 			<th></th>
	 			<th>Name</th>
	 			<th>Subject</th>
	 			<th>Marks</th>
	 			<th>Actions</th>
	 		</tr>
	 	</thead>
	 	<tbody id="student-list">
	 		<% @students.each do |student| %>
		 		<tr id="student_<%= student.id %>">
		 			<td>
		 				<span class="avatar"><%= student.name[0].upcase %></span>
		 			</td>
		 			<td data-controller="editable" data-editable-field="name" data-editable-url="<%= student_path(student) %>" contenteditable="true">
		 				<%= student.name %>
		 				</td>
		      <td data-controller="editable" data-editable-field="subject_name" data-editable-url="<%= student_path(student) %>" contenteditable="true"><%= student.subject_name %></td>
		      <td data-controller="editable" data-editable-field="marks" data-editable-url="<%= student_path(student) %>" contenteditable="true" class="student-marks-<%= student.id %>"><%= student.marks %></td>
		 			<td>
		 				<div class="dropdown">
						  <button class="btn btn-dark dropdown-toggle btn-sm" type="button" data-bs-toggle="dropdown" aria-expanded="false">
						  </button>
						  <ul class="dropdown-menu rounded-0">
						  	<%= link_to 'Edit', edit_student_path(student), class: "dropdown-item", data: { controller: "bs-modal-form" } %>
		 						<%= link_to 'Delete', student_path(student), class: "dropdown-item",  data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
						  </ul>
						</div>
		 			</td>
		 		</tr>
	 		<% end %>
	 	</tbody>
	 </table>
 </div>
	 <div>
	 	<%= link_to "New Student", new_student_path, class: "btn btn-dark rounded-0 mt-3", data: { controller: "bs-modal-form" } %>
	 </div>
</div>

app/views/students/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'shared/turbo_modal', modal_title: 'Create Student', form_partial: 'students/form' %>
<% end %>

app/views/students/update.turbo_stream.erb
<%= turbo_stream.replace "student_#{@student.id}", partial: "students/student", locals: { student: @student } %>

app/views/teachers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/teachers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>